<a href="https://colab.research.google.com/github/RAJUKM879/CLG/blob/main/_rkm_CLG_002_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.sum())

10


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.mean())

2.5


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.min())

1


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.max())

4


In [ ]:
import numpy as np
import random
array = np.random.randint(16,size=(4,4))
print("Input Array: \n",array)
print("largest number in x axis: ",np.max(array,axis=1))
print("largest number in y axis: ",np.max(array,axis=0))



Input Array: 
 [[ 5  4  1  7]
 [14 15  0 10]
 [ 1  2  5  9]
 [ 0  7  3  6]]
largest number in x axis:  [ 7 15  9  7]
largest number in y axis:  [14 15  5 10]


In [ ]:
import numpy as np
import random
array = np.random.randint(16,size=(4,4))
print("Input Array: \n",array)

print("Smallest number in x axis: ",np.min(array,axis=1))
print("Smallest number in y axis: ",np.min(array,axis=0))

Input Array: 
 [[ 4 14  4  3]
 [ 0 14 15 13]
 [14 12 11 14]
 [12  3  9  3]]
Smallest number in x axis:  [ 3  0 11  3]
Smallest number in y axis:  [0 3 4 3]


In [ ]:
print(arr.std())

1.118033988749895


In [ ]:



print(np.sin(arr))


[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [ ]:
arr = np.array([1, 2, 3])
print(arr + 2)


[3 4 5]


In [ ]:
import numpy as np
import random

array = np.random.randint([1,2,3,4])
squared = list(map(lambda x: x**2, arr))
print("Squared using map:", squared)
#Example of map()


Squared using map: [np.int64(1), np.int64(4), np.int64(9)]


In [ ]:
def square(number):
    return number * number

nums = [1, 2, 3, 4]
squared_numbers = list(map(square, nums))

print(squared_numbers)






[1, 4, 9, 16]


In [ ]:
nums1= [1,2,3,4,5,6]
squareOfnums1 = list(map(lambda n:n*n,nums1))
print(squareOfnums1)

[1, 4, 9, 16, 25, 36]


In [ ]:
def is_even(n):
    if n % 2 ==0:
        return True
    else:
        return False

nums = [1,2,3,4]
evens = list(filter(is_even,nums))
print(evens)

[2, 4]


In [ ]:
from functools import reduce

def sum_all(a, b):
    return a + b

nums = [1, 2, 3, 4]
total = reduce(sum_all, nums)

print(total)


10


In [ ]:
total = reduce(lambda x, y: x + y, arr)
print("Sum using reduce:", total)


Sum using reduce: 6


In [ ]:
import pandas as pd
data = pd.Series([10, 20, 30, 40], index=['a', 'b', 'c', 'd'])
print(data)

a    10
b    20
c    30
d    40
dtype: int64


In [ ]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['Delhi', 'Mumbai', 'Bangalore']
}
df = pd.DataFrame(data)
print(df)

      Name  Age       City
0    Alice   25      Delhi
1      Bob   30     Mumbai
2  Charlie   35  Bangalore


In [ ]:
import pandas as pd
df = pd.read_csv('rkm-001.csv')


df.to_csv('output.csv', index=False)

df.head()
df.tail()
df.info()
df.describe()
df.columns
df.shape




print(df['Name'])

print(df.loc[0])
print(df.iloc[2])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    5 non-null      object
 1   Age     5 non-null      int64 
 2   City    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes
0      Alice
1        Bob
2    Charlie
3      David
4        Eva
Name: Name, dtype: object
Name       Alice
Age           30
City    New York
Name: 0, dtype: object
Name    Charlie
Age          35
City    Chicago
Name: 2, dtype: object


In [ ]:
filtered = df[df['Age'] > 25]
print(filtered)


      Name  Age      City
0    Alice   30  New York
2  Charlie   35   Chicago
3    David   28   Houston


In [ ]:
import pandas as pd
# list of strings
lst = ['Apple', 'Mango', 'Banana', 'Pine Apple', 'Grapes', 'Watermelon']
# Calling DataFrame constructor on list
df = pd.DataFrame(lst)
print(df)


            0
0       Apple
1       Mango
2      Banana
3  Pine Apple
4      Grapes
5  Watermelon


In [ ]:

# Creating a Sample DataFrame
import pandas as pd
data = {
    'Department': ['HR', 'HR', 'IT', 'IT', 'Finance', 'Finance'],
    'Employee': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
    'Salary': [50000, 55000, 60000, 65000, 70000, 72000],
    'Age': [25, 30, 28, 32, 40, 38]
}
df = pd.DataFrame(data)
print(df)

  Department Employee  Salary  Age
0         HR    Alice   50000   25
1         HR      Bob   55000   30
2         IT  Charlie   60000   28
3         IT    David   65000   32
4    Finance      Eva   70000   40
5    Finance    Frank   72000   38


In [ ]:

print(df['Salary'].mean())
# Max age
print(df['Age'].max())

# Group by Department and get mean salary
grouped = df.groupby('Department')['Salary'].mean()
print(grouped)
print("/n")

#  Multiple Aggregation Functions
# Get multiple aggregations
grouped = df.groupby('Department')['Salary'].agg(['mean', 'max', 'min'])
print(grouped)

#  Group By Multiple Columns
# Add another field to group (if exists)
df['Location'] = ['Mumbai', 'Delhi', 'Mumbai', 'Delhi', 'Mumbai', 'Delhi']
# Group by Department and Location
grouped = df.groupby(['Department', 'Location'])['Salary'].mean()
print(grouped)

#  Using agg() with Custom Functions
# Custom aggregation on multiple columns
result = df.groupby('Department').agg({
    'Salary': 'mean',
    'Age': ['min', 'max']
})
print(result)

62000.0
40
Department
Finance    71000.0
HR         52500.0
IT         62500.0
Name: Salary, dtype: float64
/n
               mean    max    min
Department                       
Finance     71000.0  72000  70000
HR          52500.0  55000  50000
IT          62500.0  65000  60000
Department  Location
Finance     Delhi       72000.0
            Mumbai      70000.0
HR          Delhi       55000.0
            Mumbai      50000.0
IT          Delhi       65000.0
            Mumbai      60000.0
Name: Salary, dtype: float64
             Salary Age    
               mean min max
Department                 
Finance     71000.0  38  40
HR          52500.0  25  30
IT          62500.0  28  32


In [ ]:
#  Creating DataFrame from dict:
import pandas as pd
# intialise data of lists.
data ={'Name':['Tom', 'nick', 'krish', 'jack'],
       'Age':[20, 21, 19, 18]
}
# Create DataFrame
df = pd.DataFrame(data)
print(df)

    Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18
